config/routes.rb
Rails.application.routes.draw do
  resources :games

  resources :groups

  resources :countries

  resources :users

  resources :predictions

  root 'users#ranking'

  match 'help' => 'help#index', :via => :get

  match 'graph' => 'graphs#index', :via => :get
  match 'graph/get_graph' => 'graphs#get_graph', :via => :get

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  validates :country1_goals, :country2_goals, numericality: {greater_than_or_equal_to: 0, allow_nil: true}
  validate :goals_presence

  before_save :set_done
  after_save :update_points, if: :done

  def goals_presence
    if country1_goals.blank? and country2_goals.present?
      errors.add(:country1_goals, 'Resultado incompleto')
    elsif country2_goals.blank? and country1_goals.present?
      errors.add(:country2_goals, 'Resultado incompleto')
    end
  end

  def set_done
    self.done = country1_goals.present? and country2_goals.present?
    self.points = nil unless self.done
    true
  end

  def update_points
    if self.done and self.game.played
      points = 0
      # Acierta marcador
      if self.country1_goals == self.game.country1_goals and self.country2_goals == self.game.country2_goals
        points = 3
      else
        p_diff = self.country1_goals - self.country2_goals
        g_diff = self.game.country1_goals - self.game.country2_goals
        # Acierta ganador o empate
        if ((p_diff == 0 and g_diff == 0) or (p_diff < 0 and g_diff < 0) or (p_diff > 0 and g_diff > 0))
          points = 1
        end
      end
      self.update_column(:points, points)
    end
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :set_prediction, only: [:show, :edit, :update, :destroy]

  # GET /predictions
  # GET /predictions.json
  def index
    @predictions = Prediction.all
  end

  # GET /predictions/1
  # GET /predictions/1.json
  def show
  end

  # GET /predictions/new
  def new
    @prediction = Prediction.new
  end

  # GET /predictions/1/edit
  def edit
    redirect_to user_path(@prediction.user_id) unless @prediction.game.defined
  end

  # POST /predictions
  # POST /predictions.json
  def create
    @prediction = Prediction.new(prediction_params)

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to user_path(@prediction.user), notice: 'Prediction was successfully created.' }
        format.json { render :show, status: :created, location: @prediction }
      else
        format.html { render :new }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predictions/1
  # PATCH/PUT /predictions/1.json
  def update
    respond_to do |format|
      if @prediction.update(prediction_params)
        format.html { redirect_to user_path(@prediction.user), notice: 'Prediction was successfully updated.' }
        format.json { render :show, status: :ok, location: @prediction }
      else
        format.html { render :edit }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1
  # DELETE /predictions/1.json
  def destroy
    @prediction.destroy
    respond_to do |format|
      format.html { redirect_to predictions_url, notice: 'Prediction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prediction
      @prediction = Prediction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prediction_params
      params.require(:prediction).permit(:game_id, :country1_id, :country2_id, :country1_goals, :country2_goals)
    end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<%= form_for @prediction, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Resultado", :class => 'control-label' %>
    <div class="controls">
      <%= "#{@prediction.game.country1.name}" %> <%= image_tag "#{@prediction.game.country1.code}.png", class: 'flag-icon' %> 
      <%= f.text_field :country1_goals, :class => 'text_field goal_field' %> : 
      <%= f.text_field :country2_goals, :class => 'text_field goal_field' %> 
      <%= image_tag "#{@prediction.game.country2.code}.png", class: 'flag-icon' %> 
      <%= "#{@prediction.game.country2.name}" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Aceptar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar',
                user_path(@prediction.user_id), :class => 'btn' %>
  </div>
<% end %>

app/views/predictions/edit.html.erb
<%- model_class = Prediction -%>
<div class="page-header">
  <h1>Editar predicción</h1>
</div>
<%= render :partial => 'form' %>

app/views/predictions/index.html.erb
<%- model_class = Prediction -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:game_id) %></th>
      <th><%= model_class.human_attribute_name(:country1_id) %></th>
      <th><%= model_class.human_attribute_name(:country2_id) %></th>
      <th><%= model_class.human_attribute_name(:country1_goals) %></th>
      <th><%= model_class.human_attribute_name(:country2_goals) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @predictions.each do |prediction| %>
      <tr>
        <td><%= link_to prediction.id, prediction_path(prediction) %></td>
        <td><%= prediction.user_id %></td>
        <td><%= prediction.game_id %></td>
        <td><%= prediction.country1_id %></td>
        <td><%= prediction.country2_id %></td>
        <td><%= prediction.country1_goals %></td>
        <td><%= prediction.country2_goals %></td>
        <td><%=l prediction.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_prediction_path(prediction), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      prediction_path(prediction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_prediction_path,
            :class => 'btn btn-primary' %>

app/views/predictions/new.html.erb
<%- model_class = Prediction -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/predictions/show.html.erb
<%- model_class = Prediction -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @prediction.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game_id) %>:</strong></dt>
  <dd><%= @prediction.game_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country1_id) %>:</strong></dt>
  <dd><%= @prediction.country1_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country2_id) %>:</strong></dt>
  <dd><%= @prediction.country2_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country1_goals) %>:</strong></dt>
  <dd><%= @prediction.country1_goals %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country2_goals) %>:</strong></dt>
  <dd><%= @prediction.country2_goals %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              predictions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_prediction_path(@prediction), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              prediction_path(@prediction),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>