config/routes.rb
Rails.application.routes.draw do
  resources :games

  resources :groups

  resources :countries

  resources :users

  resources :predictions

  root 'users#ranking'

  match 'help' => 'help#index', :via => :get

  match 'graph' => 'graphs#index', :via => :get
  match 'graph/get_graph' => 'graphs#get_graph', :via => :get

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :predictions, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  after_create :create_predictions

  def create_predictions
    transaction do
      Game.all.each do |game|
        prediction = Prediction.new
        prediction.user = self
        prediction.game = game
        prediction.save
      end
    end
  end

  def get_predictions
    Group.all.inject({}) do |hash, group|
      hash[group.id] = Prediction
        .includes(game: {country1: {}, country2: {}})
        .where(user_id: self.id)
        .where(games: {group_id: group.id})
        .order('games.date ASC')
      hash
    end
  end

  def get_points
    self.predictions.sum(:points)
  end

  def self.get_all_points
    Prediction
      .joins(:user)
      .select('user_id, users.name AS name, SUM(points) AS points')
      .group('user_id')
      .order('points DESC')
      .inject({}) do |hash, pp|
        hash[pp[:user_id]] = {name: pp[:name], points: pp[:points]}
        hash
    end
  end

  def self.get_top_3
    Prediction
      .joins(:user)
      .select('user_id, users.name AS name, SUM(points) AS points')
      .group('user_id')
      .order('points DESC')
      .limit(3)
      .inject({}) do |hash, pp|
        hash[pp[:user_id]] = {name: pp[:name], points: pp[:points]}
        hash
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def ranking
    @users_points = User.get_all_points
  end

  def show
    @groups = Group.all
    @predictions = @user.get_predictions
    @points = @user.get_points
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), notice: 'Usuario creado exitosamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'Usuario actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, 'Nombre', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Aceptar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar',
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h2>Editar usuario</h2>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h2>Usuarios</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>
          <%= link_to 'Editar usuario',
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Eliminar usuario',
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => '¿Está seguro?' },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nuevo',
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h2>Nuevo usuario</h2>
</div>
<%= render :partial => 'form' %>

app/views/users/ranking.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h2>Ranking</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Posición</th>
      <th>Nombre</th>
      <th>Puntos</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @users_points.each_with_index do |(user_id, user_info), i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= user_info[:name] %></td>
        <td><%= user_info[:points] %></td>
        <td>
          <%= link_to 'Ver Quiniela',
                      user_path(user_id), :class => 'btn btn-mini btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h2>Quiniela de <%= @user.name %></h2>
</div>
<dl class="dl-horizontal">
  <dt><strong>Total puntos:</strong></dt>
  <dd><%= @points %></dd>
</dl>

<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <% (Game::FASEDEGRUPOS .. Game::FINAL).each do |type| %>
    <li class="<%= type == Game::FASEDEGRUPOS ? 'active' : '' %>">
      <a href="#fase_<%= type %>" data-toggle="tab"><%= Game::TYPE_STRINGS[type] %></a>
    </li>
  <% end %>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="fase_<%= Game::FASEDEGRUPOS %>">
    <ul class="nav nav-tabs">
      <% @groups.each_with_index do |group, index| %>
        <li <%= index == 0 ? 'class=active' : '' %>>
          <a href="#grupo_<%= group.code %>" data-toggle="tab">Grupo <%= group.code %></a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <% @groups.each_with_index do |group, index| %>
        <div class="tab-pane <%= index == 0 ? 'active' : '' %>" id="grupo_<%= group.code %>">
          <h4>Grupo <%= group.code %></h4>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Fecha</th>
                <th><!-- Pais 1 --></th>
                <th><!-- Goles pais 1 --></th>
                <th><!-- Guion --></th>
                <th><!-- Goles pais 2 --></th>
                <th><!-- Pais 2 --></th>
                <th>Puntos</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @predictions[group.id].each do |p| %>
                <tr>
                  <td><%= p.game.date.strftime('%Y-%m-%d') %></td>
                  <td class="right"><%= p.game.country1.name %> <%= image_tag "#{p.game.country1.code}.png", class: 'flag-icon' %></td>
                  <td class="right"><%= p.country1_goals.nil? ? '-' : p.country1_goals %></td>
                  <td class="center">:</td>
                  <td class="left"><%= p.country2_goals.nil? ? '-' : p.country2_goals %></td>
                  <td class="left"><%= image_tag "#{p.game.country2.code}.png", class: 'flag-icon' %> <%= p.game.country2.name %></td>
                  <td><%= p.points %></td>
                  <td>
                    <%= link_to 'Editar predicción', edit_prediction_path(p), :class => 'btn btn-mini' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
        <% end %>
      </div>
  </div>
  <div class="tab-pane" id="fase_<%= Game::OCTAVOS %>">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Número</th>
          <th>Fecha</th>
          <th><!-- Pais 1 --></th>
          <th><!-- Goles pais 1 --></th>
          <th><!-- Guion --></th>
          <th><!-- Goles pais 2 --></th>
          <th><!-- Pais 2 --></th>
          <th>Puntos</th>
        </tr>
      </thead>
      <tbody>
        <% Prediction.includes(:game).where(user_id: @user.id, games: {type: Game::OCTAVOS}).each do |p| %>
          <tr>
            <td><%= p.game.number %></td>
            <td><%= p.game.date.strftime('%Y-%m-%d') %></td>
            <% unless p.game.country1_id.nil? %>
              <td class="right"><%= p.game.country1.name %> <%= image_tag "#{p.game.country1.code}.png", class: 'flag-icon' %></td>
            <% else %>
              <td class="right">Primero Grupo <%= p.game.first_place_group.code %> <%= image_tag "none.png", class: 'flag-icon' %></td>
            <% end %>
            <td class="right"><%= p.country1_goals.nil? ? '-' : p.country1_goals %></td>
            <td class="center">:</td>
            <td class="left"><%= p.country2_goals.nil? ? '-' : p.country2_goals %></td>
            <% unless p.game.country2_id.nil? %>
              <td class="left"><%= image_tag "#{p.game.country2.code}.png", class: 'flag-icon' %> <%= p.game.country2.name %></td>
            <% else %>
              <td class="left"><%= image_tag "none.png", class: 'flag-icon' %> Segundo Grupo <%= p.game.second_place_group.code %></td>
            <% end %>
            <td><%= p.points %></td>
            <td>
            <% if p.game.defined %>
              <%= link_to 'Editar predicción', edit_prediction_path(p), :class => 'btn btn-mini' %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% (Game::CUARTOS .. Game::FINAL).each do |type| %>
    <div class="tab-pane" id="fase_<%= type %>">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Número</th>
            <th>Fecha</th>
            <th><!-- Pais 1 --></th>
            <th><!-- Goles pais 1 --></th>
            <th><!-- Guion --></th>
            <th><!-- Goles pais 2 --></th>
            <th><!-- Pais 2 --></th>
            <th>Puntos</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% Prediction.includes(:game).where(games: {type: type}, user_id: @user.id).each do |p| %>
            <tr>
              <td><%= p.game.number %></td>
              <td><%= p.game.date.strftime('%Y-%m-%d') %></td>
              <% unless p.game.country1_id.nil? %>
                <td class="right"><%= p.game.country1.name %> <%= image_tag "#{p.game.country1.code}.png", class: 'flag-icon' %></td>
              <% else %>
                <td class="right"><%= type != Game::TERCERO ? 'Ganador' : 'Perdedor' %> juego <%= p.game.previous_match1.number %> <%= image_tag "none.png", class: 'flag-icon' %></td>
              <% end %>
              <td class="right"><%= p.game.country1_goals.nil? ? '-' : p.game.country1_goals %></td>
              <td class="center">:</td>
              <td class="left"><%= p.game.country2_goals.nil? ? '-' : p.game.country2_goals %></td>
              <% unless p.game.country2_id.nil? %>
                <td class="left"><%= image_tag "#{p.game.country2.code}.png", class: 'flag-icon' %> <%= p.game.country2.name %></td>
              <% else %>
                <td class="left"><%= image_tag "none.png", class: 'flag-icon' %> <%= type != Game::TERCERO ? 'Ganador' : 'Perdedor' %> juego <%= p.game.previous_match2.number %></td>
              <% end %>
              <td><%= p.points %></td>
              <td>
              <% if p.game.defined %>
                <%= link_to 'Editar predicción', edit_prediction_path(p), :class => 'btn btn-mini' %>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>