config/routes.rb
Rails.application.routes.draw do
  resources :games

  resources :groups

  resources :countries

  resources :users

  resources :predictions

  root 'users#ranking'

  match 'help' => 'help#index', :via => :get

  match 'graph' => 'graphs#index', :via => :get
  match 'graph/get_graph' => 'graphs#get_graph', :via => :get

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiniela Brasil 2014</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body data-no-turbolink="true">
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Quiniela <%= image_tag "logo_small.png", alt: "Brasil 2014", width: "70", id: "logo" %></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Ranking de Usuarios", "/" %></li>
              <li><%= link_to "Resultados", games_path %></li>
              <li><%= link_to "Administrar Usuarios", users_path %></li>
              <li><%= link_to "Grafo", "/graph" %></li>
              <li><%= link_to "Ayuda", "/help" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar-nav">
            <h4>Top 3 Usuarios</h4>
            <ol class="nav nav-list">
              <% User.get_top_3.each do |user_id, user_data| %>
              <li><%= link_to "#{user_data[:name]} (#{user_data[:points].nil? ? 0 : user_data[:points]})", user_path(user_id) %></li>
              <% end %>
              <li><a href="/">Ver todos</a></li>
            </ol>
            <h4>Realizado por</h4>
            <ul>
              <li>Eleazar Meza CI 17782097</li>
              <li>German Gómez CI 84336130</li>
            </ul>
          </div>
        </div>
      </div>

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>